defaultSemverRangePrefix: ""

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmRegistryServer: "https://registry.npmjs.org"

# Necessary for installing Trulioo private packages
npmRegistries:
  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: 4ae7842d-92db-4c94-82fb-99501fcec15b
