trigger:
  - main
  - develop

pool:
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: devops-tf
      name: devops-tf
      type: git
      ref: develop

stages:
  - stage: ParallelJobs
    jobs:
      - job:
        steps:
          - bash: echo "Start Parallel Build for all envs"

  - stage: "Build_Dev"
    dependsOn: ParallelJobs
    jobs:
      - template: Pipeline/deploy/next-ci.yml@devops-tf
        parameters:
          # yarncachefolder: "$(Pipeline.Workspace)/.yarn"
          usesonar: "true"
          auth0login: /login
          apimurl: https://apimaz-weu-tfo-mvp-dev.azure-api.net
          Googleanalyticsid: $(gaid)
          SERVER_PRIVATE_KEY: $(serverprivatekey)
          NEXT_PUBLIC_KEY_ENCRYPTION: $(publickeyencryption)
          NEXT_PUBLIC_APP_INSIGHTS_INSTRUMENTATION_KEY: $(appinsightkey)
          NEXT_PUBLIC_INSIDER_KEY_ID: $(NEXT_PUBLIC_INSIDER_KEY_ID)
          NEXT_PUBLIC_BASE_URL: $(NEXT_PUBLIC_BASE_URL)
          Artifactsfolder: dev
          e2eenabled: "false"
          environmentBranch: "develop"
          variablegroupname: Dev
          doDeploy: ${{ eq(variables['build.SourceBranchName'], 'develop') }}

  - stage: "Deploy_Frontend_dev"
    dependsOn: "Build_Dev"
    jobs:
      - template: Pipeline/deploy/next-cd.yml@devops-tf
        parameters:
          serviceconn: "TFO-AZ-STG(39f9b80d-87bb-4883-84eb-a34cf481525e)"
          environment: "Dev_FE"
          envname: "dev"
          environmentBranch: "develop"
          artifacts: "**/dev/*.zip"
          appname: "frontend"
          doDeploy: ${{ eq(variables['build.SourceBranchName'], 'develop') }}

  - stage: "Build_QA"
    dependsOn: ParallelJobs
    jobs:
      - template: Pipeline/deploy/next-ci-qa.yml@devops-tf
        parameters:
          # yarncachefolder: "$(Pipeline.Workspace)/.yarn"
          usesonar: "false"
          auth0login: /login
          apimurl: https://apimaz-weu-tfo-mvp-qa.azure-api.net
          Googleanalyticsid: $(gaid)
          SERVER_PRIVATE_KEY: $(serverprivatekey)
          NEXT_PUBLIC_KEY_ENCRYPTION: $(publickeyencryption)
          NEXT_PUBLIC_APP_INSIGHTS_INSTRUMENTATION_KEY: $(appinsightkey)
          NEXT_PUBLIC_INSIDER_KEY_ID: $(NEXT_PUBLIC_INSIDER_KEY_ID)
          NEXT_PUBLIC_BASE_URL: $(NEXT_PUBLIC_BASE_URL)
          Artifactsfolder: qa
          e2eenabled: "false"
          environmentBranch: "develop"
          variablegroupname: QA
          doDeploy: ${{ eq(variables['build.SourceBranchName'], 'develop') }}

  - stage: "Deploy_Frontend_QA"
    dependsOn: "Build_QA"
    jobs:
      - template: Pipeline/deploy/next-cd.yml@devops-tf
        parameters:
          serviceconn: "TFO-AZ-STG(39f9b80d-87bb-4883-84eb-a34cf481525e)"
          environment: "QA_FE"
          envname: "qa"
          environmentBranch: "develop"
          artifacts: "**/qa/*.zip"
          appname: "frontend"
          doDeploy: ${{ eq(variables['build.SourceBranchName'], 'develop') }}
